name: Push to the aur
on:
  push:
    tags:
      - v*

jobs: 
  aur:
     name: Build AUR package
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
       - name: Extract tag version without v
         id: extract_version
         run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//')"
       - name: Setup SSH key
         run: |
           mkdir -p ~/.ssh
           echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/aur
           chmod 600 ~/.ssh/aur
           ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
           echo -e "Host aur.archlinux.org\n\tIdentityFile ~/.ssh/aur\n\tUser aur" > ~/.ssh/config            
       - name: Pull changes from AUR
         run: |
          sed -i "s/pkgver=.*/pkgver=${{ steps.extract_version.outputs.version }}/" PKGBUILD
          git clone aur@aur.archlinux.org:kill-net.git
          cp -u ./README.md kill-net/README.md
          cp -u ./LICENSE kill-net/LICENSE
          cp -u ./PKGBUILD kill-net/PKGBUILD
          cd kill-net
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
       - name: Validate package
         uses: hapakaien/archlinux-package-action@v2
         with:
           path: kill-net
           flags: ''
           namcap: false
           srcinfo: true
       - name: Push to AUR
         run: |
           cd kill-net
           cat PKGBUILD
           git add .
           git commit -m "update to ${{ steps.extract_version.outputs.version }}"
           git push
       - uses: EndBug/add-and-commit@v9
         with:
           default_author: github_actions
          
