name: Push to the aur
on:
  push:
    tags:
      - v*

jobs: 
  aur:
     name: Build AUR package
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
       - name: Extract tag version without v
         id: extract_version
         run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//')"
       - name: Update PKGBUILD with extracted version
         run: sed -i "s/pkgver=.*/pkgver=${{ steps.extract_version.outputs.version }}/" PKGBUILD
       - name: Validate package
         uses: hapakaien/archlinux-package-action@v2
         with:
           flags: ''
           namcap: false
           srcinfo: true
       - name: Setup ssh key
         with:
          key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          name: aur
          known_hosts: aur.archlinux.org
          config: |
            Host aur.archlinux.org
              IdentityFile ~/.ssh/aur
              User aur
       - name: Push changes to AUR
         run: |
          ssh aur@aur.archlinux.org help
