name: Push to the aur
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs: 
  aur:
     name: Build AUR package
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
       - name: Extract tag version without v
         id: extract_version
         run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//')"
       - name: Update PKGBUILD with extracted version
         run: sed -i "s/pkgver=.*/pkgver=${{ steps.extract_version.outputs.version }}/" PKGBUILD
       - name: Validate package
         uses: hapakaien/archlinux-package-action@v2
         with:
           flags: ''
           namcap: false
           srcinfo: true
       - name: Setup SSH key
         run: |
           mkdir -p ~/.ssh
           echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/aur
           chmod 600 ~/.ssh/aur
           ssh-add ~/.ssh/aur
           ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
           echo -e "Host aur.archlinux.org\n\tIdentityFile ~/.ssh/aur\n\tUser aur" > ~/.ssh/config            
       - name: Push changes to AUR
         run: |
          ssh aur@aur.archlinux.org help
