name: Push to the aur
on:
  push:
    tags:
      - v*

jobs: 
  aur:
     name: Build AUR package
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
       - name: Update Version
         run: sed -i "s/pkgver=.*/pkgver=${{ needs.version.version.outputs.version }}/" PKGBUILD
       - name: Push changes to AUR
         uses: datakrama/push-aur-action@v1
         with:
           pkgname: 'kill-net'
           git_username: ${{ secrets.GIT_USERNAME }}
           git_email: ${{ secrets.GIT_EMAIL }}
           private_ssh_key: ${{ secrets.AUR_PRIVATE_SSH_KEY }}
